import 'package:holol_POS/core/services/invoices/invoice_document.dart';

InvoiceDocument buildPrinterTestDocument() {
  return InvoiceDocument(
    saleId: 'TEST',
    localInvoiceNo: 'TEST-RTL-QR',
    invoiceDateTime: DateTime.now(),
    invoiceTypeLabel: 'فاتورة ضريبية مبسطة',
    statusCode: 'completed',
    statusLabel: 'اختبار',
    syncStatusLabel: 'اختبار محلي',
    seller: const InvoiceSellerInfo(
      name: 'متجر حلول بلس',
      taxNumber: '300000000000003',
      commercialRegistration: '1010000000',
      address: 'الرياض - المملكة العربية السعودية',
      phone: '0550000000',
    ),
    branch: const InvoiceBranchInfo(
      id: 'TEST',
      name: 'الفرع الرئيسي',
      taxNumber: '300000000000003',
      commercialRegistration: '1010000000',
      city: 'الرياض',
      address: 'طريق الملك فهد',
    ),
    terminal: const InvoiceTerminalInfo(terminalId: 'POS-01', useTax: true),
    cashier: const InvoiceCashierInfo(userId: 'TEST', name: 'كاشير تجريبي'),
    customer: const InvoiceCustomerInfo(
      name: 'عميل نقدي',
      taxNumber: '399999999999993',
    ),
    lines: const [
      InvoiceLineDocument(
        itemId: 'TEST_ITEM_1',
        itemName:
            'منتج تجريبي باسم عربي طويل لاختبار التفاف النص داخل الفاتورة الحرارية',
        unitId: 'EA',
        unitName: 'حبة',
        quantity: 2,
        unitPrice: 10,
        lineSubtotal: 20,
        discountAmount: 1,
        taxRate: 15,
        taxAmount: 2.85,
        lineTotal: 21.85,
        allowDiscount: true,
        priceOverridden: false,
        display: InvoiceLineDisplay(
          quantity: '2',
          unitPrice: '10.00 ر.س',
          lineSubtotal: '20.00 ر.س',
          discountAmount: '1.00 ر.س',
          taxRate: '15%',
          taxAmount: '2.85 ر.س',
          lineTotal: '21.85 ر.س',
        ),
      ),
      InvoiceLineDocument(
        itemId: 'TEST_ITEM_2',
        itemName: 'Coffee Beans 250g',
        unitId: 'EA',
        unitName: 'Each',
        quantity: 1,
        unitPrice: 35,
        lineSubtotal: 35,
        discountAmount: 0,
        taxRate: 15,
        taxAmount: 5.25,
        lineTotal: 40.25,
        allowDiscount: true,
        priceOverridden: false,
        display: InvoiceLineDisplay(
          quantity: '1',
          unitPrice: '35.00 ر.س',
          lineSubtotal: '35.00 ر.س',
          discountAmount: '0.00 ر.س',
          taxRate: '15%',
          taxAmount: '5.25 ر.س',
          lineTotal: '40.25 ر.س',
        ),
      ),
    ],
    taxSummary: const [
      InvoiceTaxDocument(
        taxRate: 15,
        taxableAmount: 54,
        taxAmount: 8.10,
        displayRate: '15%',
        displayTaxableAmount: '54.00 ر.س',
        displayTaxAmount: '8.10 ر.س',
      ),
    ],
    payments: const [
      InvoicePaymentDocument(
        paymentMethodId: 'CARD',
        paymentMethodCode: 'mada',
        methodName: 'مدى',
        amount: 62.10,
        referenceNo: 'AUTH-123456',
        manualRecord: false,
        displayMethod: 'مدى',
        displayAmount: '62.10 ر.س',
      ),
    ],
    totals: const InvoiceTotalsDocument(
      subtotal: 55,
      discountTotal: 1,
      taxTotal: 8.10,
      netTotal: 62.10,
      paidTotal: 62.10,
      remainingTotal: 0,
      changeAmount: 0,
      displaySubtotal: '55.00 ر.س',
      displayDiscountTotal: '1.00 ر.س',
      displayTaxTotal: '8.10 ر.س',
      displayNetTotal: '62.10 ر.س',
      displayPaidTotal: '62.10 ر.س',
      displayRemainingTotal: '0.00 ر.س',
      displayChangeAmount: '0.00 ر.س',
    ),
    qrPayload: 'TEST-RTL-QR|300000000000003|62.10|8.10',
    notes: 'اختبار طباعة: عربي + English + QR + خصم + مرجع دفع.',
    arabicPrintNotice:
        'إذا كانت هذه الفاتورة واضحة فالملف الشخصي للطابعة مناسب.',
  );
}
