import 'package:holol_POS/core/services/invoices/invoice_document.dart';

InvoiceDocument buildPrinterTestDocument() {
  return InvoiceDocument(
    saleId: 'TEST',
    localInvoiceNo: 'TEST',
    invoiceDateTime: DateTime.now(),
    invoiceTypeLabel: 'Printer test',
    statusCode: 'completed',
    statusLabel: 'Test',
    syncStatusLabel: 'Local test',
    seller: const InvoiceSellerInfo(name: 'POS'),
    branch: const InvoiceBranchInfo(id: 'TEST', name: 'POS'),
    terminal: const InvoiceTerminalInfo(terminalId: 'TEST', useTax: true),
    cashier: const InvoiceCashierInfo(userId: 'TEST', name: 'Test'),
    customer: null,
    lines: const [
      InvoiceLineDocument(
        itemId: 'TEST_ITEM',
        itemName: 'Receipt printer test item',
        unitId: 'EA',
        unitName: 'Each',
        quantity: 1,
        unitPrice: 100,
        lineSubtotal: 100,
        discountAmount: 0,
        taxRate: 1500,
        taxAmount: 15,
        lineTotal: 115,
        allowDiscount: true,
        priceOverridden: false,
        display: InvoiceLineDisplay(
          quantity: '1',
          unitPrice: '1.00 SAR',
          lineSubtotal: '1.00 SAR',
          discountAmount: '0.00 SAR',
          taxRate: '15%',
          taxAmount: '0.15 SAR',
          lineTotal: '1.15 SAR',
        ),
      ),
    ],
    taxSummary: const [],
    payments: const [],
    totals: const InvoiceTotalsDocument(
      subtotal: 100,
      discountTotal: 0,
      taxTotal: 15,
      netTotal: 115,
      paidTotal: 115,
      remainingTotal: 0,
      changeAmount: 0,
      displaySubtotal: '1.00 SAR',
      displayDiscountTotal: '0.00 SAR',
      displayTaxTotal: '0.15 SAR',
      displayNetTotal: '1.15 SAR',
      displayPaidTotal: '1.15 SAR',
      displayRemainingTotal: '0.00 SAR',
      displayChangeAmount: '0.00 SAR',
    ),
    notes: 'If this text is readable, the printer profile is configured.',
  );
}
